package com.synthora.governance;

public enum GovernanceAction {
    MASTER_PRODUCT_CREATED,
    MASTER_PRODUCT_UPDATED,
    MASTER_PRODUCT_ACTIVATED,
    MASTER_PRODUCT_DEACTIVATED,
    PRODUCT_REQUEST_APPROVED,
    PRODUCT_REQUEST_REJECTED,
    PRODUCT_INFORMATION_REQUESTED,
    PRODUCT_REQUEST_RESPONDED,
    MASTER_PRODUCT_MERGED,
    OFFERING_DEACTIVATED,
    SUPPLIER_VERIFICATION_STATUS_CHANGED
}
