spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5435/kemkendra}
    username: ${DB_USER:kemkendra_admin}
    password: ${DB_PASSWORD:postgres}

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    baseline-on-migrate: true
    out-of-order: true

  mail:
    host: ${SMTP_HOST:smtp.gmail.com}
    port: ${SMTP_PORT:587}
    username: ${SMTP_USERNAME:}
    password: ${SMTP_PASSWORD:}
    properties:
      mail:
        debug: true
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            trust: smtp.gmail.com

logging:
  level:
    root: INFO
    com.kemkendra: DEBUG
    org.springframework.mail: DEBUG

jwt:
  secret: ${JWT_SECRET:KemKendraDevSecretKeyForJwtSigning2026!}
  expiration: ${JWT_EXPIRATION:900000}
  refresh-expiration: ${JWT_REFRESH_EXPIRATION:604800000}