spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5435/kemkendra}
    username: ${DB_USER:kemkendra_admin}
    password: ${DB_PASSWORD:postgres}

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    baseline-on-migrate: true
    out-of-order: true

logging:
  level:
    root: INFO
    com.kemkendra: DEBUG
    org.springframework.mail: DEBUG

jwt:
  secret: ${JWT_SECRET:KemKendraDevSecretKeyForJwtSigning2026!}
  expiration: ${JWT_EXPIRATION:86400000}