package com.synthora.notification;

public enum NotificationType {

    // RFQ
    RFQ_CREATED,
    RFQ_SUBMITTED,
    RFQ_RECEIVED,
    RFQ_CANCELLED,
    RFQ_EXPIRED,
    RFQ_UPDATED,
    RFQ_CLOSED,

    // Quotation
    QUOTATION_SUBMITTED,
    QUOTATION_UPDATED,
    QUOTATION_REVISED,
    QUOTATION_ACCEPTED,
    QUOTATION_REJECTED,

    // Negotiation
    COUNTER_OFFER_RECEIVED,
    COUNTER_OFFER_ACCEPTED,
    COUNTER_OFFER_REJECTED,

    // Purchase Order
    PURCHASE_ORDER_CREATED,
    PO_ISSUED,
    PO_CONFIRMED,
    PO_REJECTED,
    PURCHASE_ORDER_CONFIRMED,
    PURCHASE_ORDER_PROCESSING,
    PURCHASE_ORDER_SHIPPED,
    PURCHASE_ORDER_DELIVERED,
    PURCHASE_ORDER_CANCELLED,

    // Fulfillment
    ORDER_PROCESSING_STARTED,
    ORDER_SHIPPED,
    ORDER_DELIVERED,
    ORDER_RECEIPT_CONFIRMED,

    // Documents
    DOCUMENT_UPLOADED,
    DOCUMENT_VERIFICATION_REQUIRED,
    DOCUMENT_REJECTED,
    DOCUMENT_EXPIRED,

    // Master Catalog Governance
    PRODUCT_REQUEST_SUBMITTED,
    PRODUCT_INFO_RESPONDED,
    PRODUCT_REQUEST_APPROVED,
    PRODUCT_REQUEST_REJECTED,
    PRODUCT_REQUEST_INFORMATION_REQUIRED,

    MASTER_PRODUCT_CREATED,
    MASTER_PRODUCT_UPDATED,
    MASTER_PRODUCT_DEACTIVATED,
    MASTER_PRODUCT_MERGED,

    // Supplier Verification
    SUPPLIER_VERIFICATION_STARTED,
    SUPPLIER_VERIFICATION_SUBMITTED,
    SUPPLIER_INFORMATION_REQUIRED,
    VERIFICATION_INFO_REQUESTED,
    SUPPLIER_VERIFIED,
    SUPPLIER_REJECTED,
    SUPPLIER_SUSPENDED,

    // Supplier Offering
    SUPPLIER_OFFERING_SUBMITTED,
    SUPPLIER_OFFERING_UPDATED,
    SUPPLIER_OFFERING_INFORMATION_REQUIRED,
    SUPPLIER_OFFERING_APPROVED,
    SUPPLIER_OFFERING_FLAGGED,
    SUPPLIER_OFFERING_REJECTED,
    SUPPLIER_OFFERING_SUSPENDED,
    SUPPLIER_OFFERING_DEACTIVATED,
    SUPPLIER_OFFERING_MODERATED,

    // Account Governance & Suspension
    USER_SUSPENDED,
    USER_REINSTATED,
    APPEAL_SUBMITTED,
    APPEAL_REVIEW_STARTED,
    APPEAL_INFORMATION_REQUIRED,
    APPEAL_APPROVED,
    APPEAL_REJECTED
}
