package com.synthora.seller.dto;

import java.time.LocalDateTime;
import java.util.UUID;

public record SupplierProfileResponse(
        Long supplierId,
        UUID userId,
        String name,
        String slug,
        String legalName,
        String tradeName,
        String businessType,
        String registeredAddress,
        String stateProvince,
        String city,
        String postalCode,
        String countryCode,
        String countryName,
        String businessEmail,
        String businessPhone,
        String authorizedRepresentativeName,
        String authorizedRepresentativeDesignation,
        Boolean emailVerified,
        Boolean phoneVerified,
        String website,
        String taxVatNumber,
        String companyRegistrationNumber,
        String businessDescription,
        String countriesServed,
        String primaryCategories,
        String logoUrl,
        Boolean verified,
        Integer yearsInBusiness,
        Boolean exportReady,
        String verificationStatus,
        String verificationNotes,
        String adminRequestInfoNotes,
        String supplierResponseNotes,
        LocalDateTime createdAt,
        LocalDateTime verificationUpdatedAt
) {}
