package com.kemkendra.seller.verification.dto;

import java.util.List;

public record SupplierVerificationWorkspaceDto(
        Long supplierId,
        String companyName,
        String legalName,
        String tradeName,
        String businessType,
        String logoUrl,
        String countryCode,
        String countryName,
        String stateProvince,
        String city,
        String postalCode,
        String registeredAddress,
        String businessEmail,
        String businessPhone,
        String authorizedRepresentativeName,
        String authorizedRepresentativeDesignation,
        Boolean emailVerified,
        Boolean phoneVerified,
        String website,
        String taxVatNumber,
        String companyRegistrationNumber,
        String businessDescription,
        String countriesServed,
        String primaryCategories,
        Integer yearsInBusiness,
        Boolean exportReady,
        Boolean verified,
        String verificationStatus,
        int completenessPercentage,
        SupplierCompletenessDto completenessDetails,
        List<VerificationChecklistItemDto> checklist,
        List<VerificationAuditDto> auditHistory,
        long offeringCount,
        String adminRequestNotes,
        String supplierResponseNotes,
        String verificationNotes
) {
    public SupplierVerificationWorkspaceDto(
            Long supplierId,
            String companyName,
            String legalName,
            String businessType,
            String verificationStatus,
            int completenessPercentage,
            SupplierCompletenessDto completenessDetails,
            List<VerificationChecklistItemDto> checklist,
            List<VerificationAuditDto> auditHistory,
            long offeringCount,
            String adminRequestNotes,
            String supplierResponseNotes,
            String verificationNotes
    ) {
        this(
                supplierId,
                companyName,
                legalName,
                null,
                businessType,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                false,
                false,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                false,
                false,
                verificationStatus,
                completenessPercentage,
                completenessDetails,
                checklist,
                auditHistory,
                offeringCount,
                adminRequestNotes,
                supplierResponseNotes,
                verificationNotes
        );
    }
}
