package com.kemkendra.document;

public enum DocumentCategory {
    COA,
    MSDS,
    TECHNICAL_SPECIFICATION,
    CERTIFICATION,
    QUOTATION_ATTACHMENT,
    PURCHASE_ORDER,
    INVOICE,
    PACKING_LIST,
    DELIVERY_CONFIRMATION,
    SHIPPING_DOCUMENT,
    COMPANY_REGISTRATION,
    GST_CERTIFICATE,
    TAX_CERTIFICATE,
    BUSINESS_LICENSE,
    GMP_CERTIFICATE,
    CGMP_CERTIFICATE,
    ISO_CERTIFICATE,
    EXPORT_CERTIFICATE,
    MANUFACTURING_LICENSE
}
