package com.kemkendra.document;

public enum DocumentCategory {
    // Technical & Quality
    COA,
    CERTIFICATE_OF_ANALYSIS,
    MSDS,
    TECHNICAL_SPECIFICATION,
    CERTIFICATION,
    QUALITY_CERTIFICATE,
    SAFETY_CERTIFICATE,
    GMP_CERTIFICATE,
    CGMP_CERTIFICATE,
    ISO_CERTIFICATE,
    EXPORT_CERTIFICATE,
    MANUFACTURING_LICENSE,

    // Supplier Compliance
    BUSINESS_REGISTRATION,
    COMPANY_REGISTRATION,
    TAX_REGISTRATION,
    TAX_CERTIFICATE,
    GST_CERTIFICATE,
    COMPANY_LICENSE,
    BUSINESS_LICENSE,
    OTHER_COMPLIANCE,

    // Commercial & Transaction
    RFQ_ATTACHMENT,
    QUOTATION_ATTACHMENT,
    PURCHASE_ORDER,
    INVOICE,
    INVOICE_REFERENCE,
    PACKING_LIST,
    DELIVERY_DOCUMENT,
    DELIVERY_CONFIRMATION,
    RECEIPT_DOCUMENT,
    SHIPPING_DOCUMENT,
    SHIPMENT_DOCUMENT
}
